name: Build and tests

on:
  push:
    branches: [ main, master, develop ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:
 
jobs:

########################################################################################
  make:
    name: Make
    strategy:
      fail-fast: false
      matrix:
        machine: [ubuntu-latest]
        gmake_install_command: ['gmake --version']
        compiler: [12]
        include:
        - {machine: macOS-13, gmake_install_command: 'brew install make && gmake --version', compiler: 12}
    runs-on: ['${{ matrix.machine }}']   

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: install gmake
      run: ${{ matrix.gmake_install_command }}        
    
    - name: make
      run: | 
        gmake -j CXX=g++-${{matrix.compiler}} CC=gcc-${{matrix.compiler}} STATIC_LINK=true
    - name: tar artifacts
      run: tar -cvf vclust.tar ./vclust.py ./test.py ./example ./bin/kmer-db ./bin/lz-ani ./bin/clusty ./bin/mfasta-tool
    
    - uses: actions/upload-artifact@v4
      with:
        name: executable-artifact-${{ matrix.machine }}
        path: ./vclust.tar    

########################################################################################
  pipeline:
    name: Pipeline
    needs: make
    strategy:
      fail-fast: false
      matrix:
        machine: [ubuntu-latest, macOS-13]
     
    runs-on: ['${{ matrix.machine }}']    
    
    steps:
    - uses: actions/download-artifact@v4
      with:
        name: executable-artifact-${{ matrix.machine }}
        path: ./

    - name: set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: untar artifacts
      run: |
        tar -xf vclust.tar
    
    - name: run pipeline
      run: |
        pip install pytest
        pytest test.py -k 'not test_cluster_algorithm_leiden'
