name: Self-hosted CI

on:
  pull_request:
    branches: [ master, develop ]
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:

 ########################################################################################
  checkout:
    name: Checkout
    strategy:
      matrix:
        machine: [x64_linux, x64_mac, arm64_linux, arm64_mac]
    runs-on: [self-hosted, vclust, '${{ matrix.machine }}']
    
    steps:
    - name: clean
      run: rm -rf ${{ github.workspace }}/*
    - uses: actions/checkout@v4
      with:
        submodules: recursive
    - name: Get tags
      run: | 
        cd ./3rd_party/clusty/libs/igraph
        git fetch --prune --unshallow
        echo exit code $?
        git tag --list
      continue-on-error: true

########################################################################################
  make:
    name: Make
    needs: checkout
    strategy:
      fail-fast: false
      matrix:
        machine: [x64_linux]
        platform: [avx2]
        compiler: [14]
        leiden: [true]
        include:
        - {machine: arm64_linux, platform: arm8, compiler: 12, leiden: true}
        - {machine: x64_mac, platform: avx2, compiler: 12, leiden: false}
        - {machine: arm64_mac, platform: m1, compiler: 13, leiden: false}
        
    runs-on: [self-hosted, vclust, '${{ matrix.machine }}'] 

    steps:
    - name: make
      run: make -j32 CXX=g++-${{matrix.compiler}} CC=gcc-${{matrix.compiler}} STATIC_LINK=true PLATFORM=${{ matrix.platform }} LEIDEN=${{ matrix.leiden }}

########################################################################################
  pipeline:
    name: Pipeline
    needs: make
    strategy:
      fail-fast: false
      matrix:
        machine: [x64_linux, arm64_linux]
    runs-on: [self-hosted, vclust, '${{ matrix.machine }}']
    
    steps:
    
    - name: run pipeline
      run: |
        pytest test.py
